feat: Add GetProductVersionFeatureFlag function
cryptlex/lexactivator-ruby pull request #2
Opened 2024-08-19 09:32 UTC by muneebkq

This commit adds the GetProductVersionFeatureFlag function to the LexActivator module. This function allows retrieving the feature flag status for a specific product version. It takes the name of the feature flag, a pointer to store the enabled status, a pointer to store the data associated with the feature flag, and the length of the data.

2024-08-22 04:40 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +  # @param [String] enabled
@muneebkq enabled is not a string, it should be a boolean.

2024-08-22 04:41 UTC, ahmad-kemsan requested changes
Please check the same function in other wrappers

2024-08-22 10:29 UTC, muneebkq commented on examples/LexActivator.rb
> +  # @param [String] enabled
refactor done

2024-11-13 17:48 UTC, ahmad-kemsan commented on examples/LexStatusCodes.rb
> +  LA_RELEASE_UPDATE_AVAILABLE_NOT_ALLOWED = 32,
@muneebkq This error code would be possible via CheckReleaseUpdate() only and that is not included yet.

2024-11-13 17:49 UTC, ahmad-kemsan commented on examples/LexStatusCodes.rb
> +  LA_E_TWO_FACTOR_AUTHENTICATION_CODE_INVALID = 89,
@muneebkq What about the error codes from 100 -105? They seem to be not included.

2024-11-13 17:50 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +  # @param [Integer] enabled
@muneebkq param docs for enabled would be helpful.

2024-11-13 18:23 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +    def to_string
@muneebkq `to_string` is not a very idiomatic name in Ruby, and that `to_hash` would be a more appropriate and descriptive name for a method that converts an FFI::Struct to a Hash.

2024-11-13 18:23 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +    def to_string
@muneebkq Same here for the method name

2024-11-13 18:24 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +  # @param [String] organizationAddress
@muneebkq the param is a pointer to the struct. Please update the param docs.

2024-11-13 18:24 UTC, ahmad-kemsan commented on examples/LexActivator.rb
> +  # @param [String] UserLicense
@muneebkq Same here param is a pointer to the struct.

2024-11-13 18:25 UTC, ahmad-kemsan requested changes
Please check the comments

2024-11-22 12:32 UTC, ahmad-kemsan approved these changes

2024-11-22 12:33 UTC, merged